name: build-crafter-bot
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: listing
        run: |
          find .
      - name: create version file
        run: |
          echo "(setq crafter-bot-version \"$(git rev-parse --short HEAD)\")" > version.el
      - name: after listing
        run: |
          find .
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: benoitj/crafter-bot:latest
